# Utilisez l'image officielle MySQL
FROM mysql:latest

# Définissez les variables d'environnement pour MySQL
ENV MYSQL_ROOT_PASSWORD=0000
ENV MYSQL_DATABASE=formation_management

# Copiez le script SQL d'initialisation dans le conteneur
COPY db/init.sql /docker-entrypoint-initdb.d/

# Exposez le port MySQL
EXPOSE 3306
