apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: formation
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8333
      targetPort: 8333
  type: LoadBalancer
